export const ADD_PLAYER = 'ADD_PLAYER';

export const ADD_SCORE = 'ADD_SCORE';

export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_ERROR = 'GET_TOKEN_ERROR';

export const REQUEST_TRIVIA = 'REQUEST_TRIVIA';
export const GET_TRIVIA_SUCCESS = 'GET_TRIVIA_SUCCESS';
export const GET_TRIVIA_ERROR = 'GET_TRIVIA_ERROR';
